sudo: required
  
language: python

python:
 - 3.5

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes -q docker-engine
  - docker build -t build-image:alpine --build-arg BUILD_UTILITIES_VERSION=$TRAVIS_BRANCH -f environments/build/Dockerfile environments/build
  - docker build -t build-image:xenial --build-arg BUILD_UTILITIES_VERSION=$TRAVIS_BRANCH -f environments/build/Dockerfile environments/build
  - sudo mkdir -m 777 -p /build/alpine/amd64 /build/alpine/packages
  
script: 
  - docker run -t --rm -v /build:/build build-image:alpine zsh -c "cd /src && ./setup.py install --prefix=/build/alpine/install"
  - docker run -t --rm -v /build:/build build-image:alpine sh -c "cd /build/alpine/amd64/install/ && fpm -t tar -n build-utilities -p /build/alpine/amd64/packages -a amd64 -f --prefix /usr/local --url https://github.com/aacebedo/build-utilities -v $TRAVIS_BRANCH -s dir ."
  - docker build -t run-image:alpine --build-arg BUILD_UTILITIES_VERSION=$TRAVIS_BRANCH -f environments/run/Dockerfile environments/run

after_success:
  - sudo chmod -R a+rwX /build
  - mv /build/alpine/amd64/packages/build-utilities.tar /build/alpine/amd64/packages/build-utlities.alpine.amd64.$TRAVIS_BRANCH.tar
  
deploy:
  - provider: releases
    skip_cleanup: true
    api-key:
       secure: $GITHUB_TOKEN
    file:
      - /build/alpine/amd64/packages/build-utilities.alpine.amd64.$TRAVIS_BRANCH.tar
    on:
      tags: true
