sudo: required
  
language: python

python:
 - 3.5

install:
  - pip install gitpython
  
services:
  - docker

before_install:
  - sudo apt-get update
  - > 
     sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" 
     -y --force-yes -q docker-engine

script:
  - > 
     docker build -t aacebedo/build-utilities:${TRAVIS_BRANCH}_amd64 
     --build-arg BRANCH_OR_REVISION=${TRAVIS_BRANCH} environments/run
      
deploy:
  - provider: script
    script: docker login -u ${BINTRAY_USERNAME} -p ${BINTRAY_APIKEY} -e $BINTRAY_EMAIL aacebedo-docker-build-utilities-docker.bintray.io && docker tag aacebedo/build-utilities:${TRAVIS_BRANCH}_amd64 aacebedo-docker-build-utilities-docker.bintray.io/build-utilities:${TRAVIS_BRANCH}_amd64 && docker tag aacebedo/build-utilities:${TRAVIS_BRANCH}_amd64 aacebedo-docker-build-utilities-docker.bintray.io/build-utilities:latest && docker push aacebedo-docker-build-utilities-docker.bintray.io/build-utilities:latest && docker push aacebedo-docker-build-utilities-docker.bintray.io/build-utilities:${TRAVIS_BRANCH}_amd64    
    on:
      tags: true
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      tags: true
